[package]
name = "lnd-rs"
version = "0.1.0"
authors = ["lsunsi <sunsi.lucas@gmail.com>", "Luiz Parreira <luizfilipester@gmail.com.br>"]
edition = "2018"

[lib]
name = "lnd"

[dependencies]
tonic = "0.3.1"
prost = "0.6.1"
openssl = "0.10.33"
hyper = "0.13.10"
hyper-openssl = "0.8.1"
hex = "0.4.3"

[build-dependencies.tonic-build]
version = "0.3.1"
default-features = false
features = ["transport", "prost"]
