[package]
name = "lnd-rs"
version = "0.1.0"
authors = ["lsunsi <sunsi.lucas@gmail.com>", "Luiz Parreira <luizfilipester@gmail.com.br>"]
edition = "2018"

[lib]
name = "lnd"

[dependencies]
tonic = "0.3"
prost = "0.6"
openssl = "0.10"
hyper = "0.13"
hyper-openssl = "0.8"
hex = "0.4"
thiserror = "1.0"

[build-dependencies]
tonic-build = "0.3"
