[package]
name = "lnd-rs"
version = "0.1.0"
authors = ["lsunsi <lsunsi@pm.me>", "Luiz Parreira <luizfilipester@gmail.com.br>"]
edition = "2021"

[lib]
name = "lnd"

[dependencies]
tonic = { version = "0.6", features = ["transport", "codegen", "prost"], default-features = false }
prost = { version = "0.9", default-features = false }
openssl = { version = "0.10", default-features = false }
hyper = { version = "0.14", default-features = false }
hyper-openssl = { version = "0.9", default-features = false }
hex = { version = "0.4", features = ["std"], default-features = false }
thiserror = { version = "1.0", default-features = false }

[build-dependencies]
tonic-build = "0.6"
