name: lnd-rs checks

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo +stable build --all-targets
